/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Link: typeof import('./src/components/Link.vue')['default']
    MemberCard: typeof import('./src/components/member/MemberCard.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    PostCard: typeof import('./src/components/post/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TitleInput: typeof import('./src/components/title/TitleInput.vue')['default']
    TodoItem: typeof import('./src/components/todos/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/todos/TodoList.vue')['default']
  }
}
